version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: user-api-db-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=user_api_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: